if(MSVC)
  set(RF_WARN_COMMON /W4 /WX)
else()
  set(RF_WARN_COMMON -Wall -Wextra -Werror)
endif()
add_executable(example_basic basic.cpp)
target_link_libraries(example_basic PRIVATE ReservationFabric::ReservationFabric)
target_compile_options(example_basic PRIVATE ${RF_WARN_COMMON})
add_executable(example_scenarios example_scenarios.cpp)
target_link_libraries(example_scenarios PRIVATE ReservationFabric::ReservationFabric)
target_compile_options(example_scenarios PRIVATE ${RF_WARN_COMMON})
